#ifndef SRC_RENDERER_VULKAN_BUFFER_STRUCTURES_MODELTRANSFORM_H_
#define SRC_RENDERER_VULKAN_BUFFER_STRUCTURES_MODELTRANSFORM_H_

#include "util/include/glm.h"

struct ModelTransform {
  alignas(16) glm::mat4 transform;
};

#endif  // SRC_RENDERER_VULKAN_BUFFER_STRUCTURES_MODELTRANSFORM_H_
