#ifndef VULKAN_SRC_VULKAN_STRUCTURES_SEMAPHORECREATEINFO_H
#define VULKAN_SRC_VULKAN_STRUCTURES_SEMAPHORECREATEINFO_H

#include <vulkan/vulkan_core.h>

#include "types.h"
#include "define_structure.h"

STRUCTURE_BUILDER(SemaphoreCreateInfoBuilder, VkSemaphoreCreateInfo, VK_STRUCTURE_TYPE_SEMAPHORE_CREATE_INFO)
END_STRUCTURE_BUILDER

#endif // VULKAN_SRC_VULKAN_STRUCTURES_SEMAPHORECREATEINFO_H
