#ifndef SRC_ENGINE_UI_ELEMENTS_GRIDLIST_GRIDLISTELEMENT_H_
#define SRC_ENGINE_UI_ELEMENTS_GRIDLIST_GRIDLISTELEMENT_H_

#include "GridListLayout.h"

struct GridListElement {
  GridListLayout::Row row;
};

#endif  // SRC_ENGINE_UI_ELEMENTS_GRIDLIST_GRIDLISTELEMENT_H_
