#ifndef SRC_ENGINE_UI_ELEMENTS_TOGGLEBOX_TOGGLEBOXLAYOUT_H_
#define SRC_ENGINE_UI_ELEMENTS_TOGGLEBOX_TOGGLEBOXLAYOUT_H_

#include "core/math/Rect.h"

struct ToggleBoxLayout {
  Rectu renderArea;
};

#endif  // SRC_ENGINE_UI_ELEMENTS_TOGGLEBOX_TOGGLEBOXLAYOUT_H_
