#ifndef VULKAN_SRC_RENDERER_VULKAN_API_STRUCTURES_CLEARCOLORVALUE_H_
#define VULKAN_SRC_RENDERER_VULKAN_API_STRUCTURES_CLEARCOLORVALUE_H_

#include <vulkan/vulkan.h>

#include "define_structure.h"
#include "util/types.h"

STRUCTURE_BUILDER_NO_STYPE(ClearColorValueBuilder, VkClearColorValue)
STRUCTURE_SETTER_CUSTOM_ASSIGNMENT(Float0, float, float32, float32[0])
STRUCTURE_SETTER_CUSTOM_ASSIGNMENT(Float1, float, float32, float32[1])
STRUCTURE_SETTER_CUSTOM_ASSIGNMENT(Float2, float, float32, float32[2])
STRUCTURE_SETTER_CUSTOM_ASSIGNMENT(Float3, float, float32, float32[3])
STRUCTURE_SETTER_CUSTOM_ASSIGNMENT(Int0, i32, int32, int32[0])
STRUCTURE_SETTER_CUSTOM_ASSIGNMENT(Int1, i32, int32, int32[1])
STRUCTURE_SETTER_CUSTOM_ASSIGNMENT(Int2, i32, int32, int32[2])
STRUCTURE_SETTER_CUSTOM_ASSIGNMENT(Int3, i32, int32, int32[3])
STRUCTURE_SETTER_CUSTOM_ASSIGNMENT(UInt0, u32, uint32, uint32[0])
STRUCTURE_SETTER_CUSTOM_ASSIGNMENT(UInt1, u32, uint32, uint32[1])
STRUCTURE_SETTER_CUSTOM_ASSIGNMENT(UInt2, u32, uint32, uint32[2])
STRUCTURE_SETTER_CUSTOM_ASSIGNMENT(UInt3, u32, uint32, uint32[3])
END_STRUCTURE_BUILDER

#endif  // VULKAN_SRC_RENDERER_VULKAN_API_STRUCTURES_CLEARCOLORVALUE_H_
