#ifndef SRC_RENDERER_VULKAN_API_STRUCTURES_SEMAPHORECREATEINFO_H_
#define SRC_RENDERER_VULKAN_API_STRUCTURES_SEMAPHORECREATEINFO_H_

#include <vulkan/vulkan.h>

#include "core/types.h"
#include "define_structure.h"

STRUCTURE_BUILDER(SemaphoreCreateInfoBuilder, VkSemaphoreCreateInfo,
                  VK_STRUCTURE_TYPE_SEMAPHORE_CREATE_INFO)
END_STRUCTURE_BUILDER

#endif  // SRC_RENDERER_VULKAN_API_STRUCTURES_SEMAPHORECREATEINFO_H_
