#ifndef VULKAN_SRC_RENDERER_VULKAN_API_STRUCTURES_SHADERMODULECREATEINFO_H_
#define VULKAN_SRC_RENDERER_VULKAN_API_STRUCTURES_SHADERMODULECREATEINFO_H_

#include <vulkan/vulkan.h>

#include "core/types.h"
#include "define_structure.h"

STRUCTURE_BUILDER(ShaderModuleCreateInfoBuilder, VkShaderModuleCreateInfo,
                  VK_STRUCTURE_TYPE_SHADER_MODULE_CREATE_INFO)
STRUCTURE_SETTER(CodeSize, const size_t, codeSize)
STRUCTURE_SETTER(PCode, const u32*, pCode)
END_STRUCTURE_BUILDER

#endif  // VULKAN_SRC_RENDERER_VULKAN_API_STRUCTURES_SHADERMODULECREATEINFO_H_
