#ifndef SRC_ENGINE_UI_ELEMENTS_LISTBOX_LISTBOXELEMENT_H_
#define SRC_ENGINE_UI_ELEMENTS_LISTBOX_LISTBOXELEMENT_H_

#include "ListBoxLayout.h"

struct ListBoxElement {
  ListBoxLayout::Header header;
};

#endif  // SRC_ENGINE_UI_ELEMENTS_LISTBOX_LISTBOXELEMENT_H_
