#ifndef SRC_ENGINE_COMPOSITION_PARTICLEBEHAVIOUR_H_
#define SRC_ENGINE_COMPOSITION_PARTICLEBEHAVIOUR_H_

enum class ParticleBehaviour { SpaceshipExhaust };

#endif  // SRC_ENGINE_COMPOSITION_PARTICLEBEHAVIOUR_H_
