#ifndef VULKAN_SRC_ENGINE_COMPOSITION_PARTICLEBEHAVIOUR_H_
#define VULKAN_SRC_ENGINE_COMPOSITION_PARTICLEBEHAVIOUR_H_

enum class ParticleBehaviour { SpaceshipExhaust };

#endif  // VULKAN_SRC_ENGINE_COMPOSITION_PARTICLEBEHAVIOUR_H_
