#ifndef SRC_RENDERER_VULKAN_RENDER_GRAPH_LAYOUT_PIPELINEKEY_H_
#define SRC_RENDERER_VULKAN_RENDER_GRAPH_LAYOUT_PIPELINEKEY_H_

#include "core/types.h"

using PipelineKey = u32;

#endif  // SRC_RENDERER_VULKAN_RENDER_GRAPH_LAYOUT_PIPELINEKEY_H_
