#ifndef VULKAN_SRC_RENDERER_VULKAN_PIPELINE_H_
#define VULKAN_SRC_RENDERER_VULKAN_PIPELINE_H_

#include "core/types.h"

enum Pipeline : u32 {
  PIPELINE_SKYBOX_RENDER = 1,
  PIPELINE_LIGHT_RENDER,
  PIPELINE_SPACESHIP_RENDER,
  PIPELINE_PARTICLE_COMPUTE,
  PIPELINE_PARTICLE_RENDER,
  PIPELINE_UI_RENDER,
  PIPELINE_TEXT_RENDER,
};

#endif  // VULKAN_SRC_RENDERER_VULKAN_PIPELINE_H_
