#ifndef VULKAN_SRC_GAME_COMPOSITION_RENDERTYPE_H_
#define VULKAN_SRC_GAME_COMPOSITION_RENDERTYPE_H_

enum class RenderType { Skybox, Sun, Spaceship, Particle };

#endif  // VULKAN_SRC_GAME_COMPOSITION_RENDERTYPE_H_
